services:
  app:
    build: .
    networks:
      - java-app-backend-network
    ports:
      - "${EXPOSE_APP_PORT}:8080"
    tty: true
    stdin_open: true
    depends_on:
      - db
    volumes:
      - ./:/app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_ROOT_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    networks:
      - java-app-backend-network
    ports:
      - "${EXPOSE_DATABASE_PORT}:3306"
    volumes:
      - java-app-backend-data:/var/lib/mysql

networks:
  java-app-backend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.44.0.0/24

volumes:
  java-app-backend-data:
