services:
  app:
    build: app
    volumes:
      - ./app:/app
      - tmp_data:/app/tmp
    ports:
      - "${EXPOSE_PORT}:8080"
    environment:
      - GOPROXY=${GOPROXY}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    ports:
      - "${EXPOSE_PORT}:8080"
